/* eslint-disable no-empty */
/* eslint-disable react/prop-types */
/* eslint-disable no-unused-vars */
import React, { useEffect, useState } from 'react'
import { FacebookShareButton, FacebookIcon } from 'react-share';
import { TwitterShareButton, TwitterIcon } from 'react-share';
import { WhatsappShareButton, WhatsappIcon } from 'react-share';
import { PinterestShareButton, PinterestIcon } from 'react-share';
import { RedditShareButton, RedditIcon } from 'react-share';

import { Loader, Card, FormField } from './components';

const RenderCards = ({ data, title }) => {
  if(data?.length > 0) {
    return data.map((post) => <Card key={post._id} {...post} />)
  }

  return (
    <h2 className='mt-5 font-bold text-[#6449ff] text-xl uppercase'>
      {title}
    </h2>
  )
} 

const Home = () => {
  const [loading, setLoading] = useState(false);
  const [allPosts, setAllPosts] = useState(null);

  const [searchText, setSearchText] = useState('');
  const [searchedResults, setSearchedResults] = useState(null);
  const [searchTimeout, setSearchTimeout] = useState(null);

  useEffect(() => {
    const fetchPosts = async () => {
      setLoading(true);
      
      try {
        const response = await fetch(
          'https://dall-e-lakksh.onrender.com/api/v1/post',
          {
            method: 'GET',
            headers: {
              'Content-Type': 'application/json',
            },
          })

          if(response.ok) {
            const result = await response.json();

            setAllPosts(result.data.reverse());
          }
      } catch (error) {
        alert(error)
      } finally {
        setLoading(false);
      }
    }

    fetchPosts();
  }, []);

  const handleSearchChange = (e) => {
    clearTimeout(searchTimeout);

    setSearchText(e.target.value);

    setSearchTimeout(
      setTimeout(() => {
        const searchResults = allPosts.filter((item) => item.name.
        toLowerCase().includes(searchText.toLowerCase()) || item.
        prompt.toLowerCase().includes(searchText.toLowerCase()));

        setSearchedResults(searchResults);
      }, 500)
    );
  }

  return (
    <section className='max-w-7xl mx-auto'>
      <div>
        <h1 className='font-extrabold text-[#222328] text-[32px]'>
          The Community Showcase
        </h1>
        <p className='mt-2 text-[#666e75] text-[16px] max-w[500px]'>
          Browse through a collection of imaginative and visually 
          stunning images generatted by DALL-E AI
        </p>
      </div>

      <div className='mt-12'>
        <FormField 
          LabelName="Search posts"
          type="text"
          name="text"
          placeholder="Search posts"
          value={searchText}
          handleChange={handleSearchChange}
        />
      </div>

      <div className='mt-10'>
        {loading ? (
          <div className='flex justify-center items-center'>
            <Loader />
          </div>
        ) : (
          <>
          { searchText && (
            <h2 className='font-medium text-[#666e75] text-xl mb-3'>
              Showing results for <span className='text-[#222328]'>{ searchText }</span>
            </h2>
          )}
          <div className='grid lg:grid-cols-4 sm:grid-cols-3
          xs:grid-cols-2 grid-cols-1 gap-3'>
            { searchText ? (
              <RenderCards 
                data={searchedResults}
                title="No search results found"
              />
            ) : (
              <RenderCards 
                data={allPosts}
                title="No posts found"
              />
            )}
          </div>
          </>
        )}
      </div>
      <div className='mt-8'>

            <FacebookShareButton
            url={'Look at this new art piece generated by DALL-E!'}
            quote={'Look at this new art piece generated by DALL-E!'}
            hashtag="#Dall-E #MidJourney"
            >
              <FacebookIcon size={32} round />
            </FacebookShareButton>

            <TwitterShareButton
            url={'Look at this new art piece generated by DALL-E!'}
            quote={'Look at this new art piece generated by DALL-E!'}
            hashtag="#Dall-E #MidJourney"
            className='ml-8'
            >
              <TwitterIcon size={32} round />
            </TwitterShareButton>

            <WhatsappShareButton
            url={'Look at this new art piece generated by DALL-E!'}
            quote={'Look at this new art piece generated by DALL-E!'}
            hashtag="#Dall-E #MidJourney"
            className='ml-8'
            >
              <WhatsappIcon size={32} round />
            </WhatsappShareButton>

            <PinterestShareButton
            url={'Look at this new art piece generated by DALL-E!'}
            quote={'Look at this new art piece generated by DALL-E!'}
            hashtag="#Dall-E #MidJourney"
            className='ml-8'
            >
              <PinterestIcon size={32} round />
            </PinterestShareButton>

            <RedditShareButton
            url={'Look at this new art piece generated by DALL-E!'}
            quote={'Look at this new art piece generated by DALL-E!'}
            hashtag="#Dall-E #MidJourney"
            className='ml-8'
            >
              <RedditIcon size={32} round />
            </RedditShareButton>

          </div>
    </section>
  )
}

export default Home
